[package]
name = "backend-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
cxx = "1.0.124"
llama_cpp = { version = "0.3.2", features = [ "metal" ] }
thiserror = "1.0.63"
hf-hub = "0.3.2"
serde_json = "1.0.121"
serde = "1.0.204"
usearch = { git = "https://github.com/deta/usearch", branch = "main" }
fastembed = { version = "3.12.0", features = ["ort-download-binaries"] }
html-escape = "0.2.13"
unicode-normalization = "0.1.23"
unicode-segmentation = "1.11.0"
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"
uds_windows = "1.1.0"
