version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'npm'
      - 'dependencies'
    allow:
      - dependency-type: 'all'
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'cargo'
    directory: '/packages/'
    schedule:
      interval: 'weekly'
    labels:
      - 'rust'
      - 'dependencies'
