[package]
name = "backend"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.19.0"
rusqlite = "0.25.0"
tokio = { version = "1.36.0", features = ["full"] }
# neon = "1.0.0-alpha.4"

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-8"]
