[package]
name = "backend"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.19.0"
rusqlite = { version = "0.29.0", features = ["bundled", "array"]}
rust-embed = "8.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlite-vss = { version = "0.1.2", features = ["download-libs"] }
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-8"]
