[package]
name = "backend"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
rusqlite = { version = "0.31.0", features = ["bundled", "array", "chrono", "load_extension"] }
rust-embed = "8.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
strum = { version = "0.25.0", features = ["derive"] }
rust-bert = { git = "https://github.com/guillaume-be/rust-bert", rev = "29f9a7a0ff832c742db919cbc6fd0b9c865a98ae"}
rand = "0.8.5"
text-splitter = { version = "0.6.3" }
url = "2.5.0"
crossbeam-channel = "0.5.12"
lopdf = "0.32.0"
leptess = "0.14.0"
reqwest = { version = "0.11.25", features = ["json", "stream"] }
futures = "0.3.30"

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-8"]

[patch.crates-io]
tesseract-sys = { path = "./tesseract-sys" }
leptonica-sys = { path = "./leptonica-sys" }

[build-dependencies]
pkg-config = "0.3.30"
