[package]
name = "backend"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
rusqlite = { version = "0.31.0", features = ["bundled", "array", "chrono", "load_extension"] }
rust-embed = "8.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
strum = { version = "0.25.0", features = ["derive"] }
rand = "0.8.5"
text-splitter = { version = "0.6.3" }
url = "2.5.0"
crossbeam-channel = "0.5.12"
lopdf = "0.32.0"
reqwest = { version = "0.11.25", features = ["json", "stream", "blocking"] }
futures = "0.3.30"
anyhow = "1.0.86"
bytes = "1.6.1"
unicode-segmentation = "1.11.0"
unicode-normalization = "0.1.23"
strum_macros = "0.26.4"
ytranscript = "0.1.0"
html-escape = "0.2.13"
ocrs = "0.8.0"
rten = "0.10.0"
image = "0.25.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uds_windows = "1.1.0"

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-8"]

[build-dependencies]
pkg-config = "0.3.30"
